<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RunAnalyzersDuringBuild>false</RunAnalyzersDuringBuild>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DocumentationFile>C:\Projects\SkillFundingAgency\das-qna-config-preview\src\SFA.DAS.QnA.Config.Preview.Web\SFA.DAS.QnA.Config.Preview.Web.xml</DocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\..\..\..\Users\arshed\.nuget\packages\microsoft.applicationinsights.nlogtarget\2.12.0\content\app.config.install.xdt" Link="app.config.install.xdt" />
    <None Include="..\..\..\..\..\Users\arshed\.nuget\packages\microsoft.applicationinsights.nlogtarget\2.12.0\content\app.config.uninstall.xdt" Link="app.config.uninstall.xdt" />
    <None Include="..\.editorconfig" Link=".editorconfig" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BuildBundlerMinifier" Version="3.2.449" />
    <PackageReference Include="BundlerMinifier.Core" Version="3.2.449" />
    <PackageReference Include="FluentValidation.AspNetCore" Version="11.3.0" />
    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.22.0" />
    <PackageReference Include="Microsoft.ApplicationInsights.NLogTarget" Version="2.22.0" />
    <PackageReference Include="Microsoft.Extensions.Caching.Abstractions" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.0" />
    <PackageReference Include="Microsoft.IdentityModel.Logging" Version="8.3.0" />
    <PackageReference Include="NLog.Extensions.Logging" Version="5.3.15" />
    <PackageReference Include="NLog.Web.AspNetCore" Version="5.3.15" />
    <PackageReference Include="SFA.DAS.NLog.Targets.Redis" Version="1.2.1" />
    <PackageReference Include="SFA.DAS.QnA.Api.Types" Version="0.2.302" />
    <PackageReference Include="SFA.DAS.QnA.Api.Views" Version="0.2.302" />
    <PackageReference Include="StackExchange.Redis" Version="2.8.22" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="7.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SFA.DAS.QnA.Config.Preview.Api.Client\SFA.DAS.QnA.Config.Preview.Api.Client.csproj" />
    <ProjectReference Include="..\SFA.DAS.QnA.Config.Preview.ApplyTypes\SFA.DAS.QnA.Config.Preview.Types.csproj" />
    <ProjectReference Include="..\SFA.DAS.QnA.Config.Preview.Session\SFA.DAS.QnA.Config.Preview.Session.csproj" />
    <ProjectReference Include="..\SFA.DAS.QnA.Config.Preview.Settings\SFA.DAS.QnA.Config.Preview.Settings.csproj" />
  </ItemGroup>



</Project>
