<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="13.0.1" />
    <PackageReference Include="JWT" Version="11.0.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.0" />
    <PackageReference Include="Microsoft.Identity.Client" Version="4.66.2" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Polly" Version="8.5.0" />
    <PackageReference Include="SFA.DAS.Http" Version="3.2.69" />
    <PackageReference Include="SFA.DAS.QnA.Api.Types" Version="0.2.302" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SFA.DAS.QnA.Config.Preview.ApplyTypes\SFA.DAS.QnA.Config.Preview.Types.csproj" />
    <ProjectReference Include="..\SFA.DAS.QnA.Config.Preview.Settings\SFA.DAS.QnA.Config.Preview.Settings.csproj" />
  </ItemGroup>

</Project>
